add_newline = false

[username]
# show_always = true
style_root = "red"
style_user = "purple"

[hostname]
# ssh_only = false
style = "yellow"
ssh_symbol = "ï³£ "

[localip]
disabled = true

[directory]
style = "green"
truncation_length = 5

[cmd_duration]
style = "yellow"
min_time = 5_000

[git_state]
style = "yellow"

[git_status]
format = '([\[$conflicted[$deleted](yellow)[$renamed](bright-red)[$modified](red)[$staged](green)[$untracked](purple)$ahead_behind\]]($style) )'
style = "bright-yellow"
stashed = ""
modified = "â—"
staged = "â—"
untracked = "â—"
deleted = "â—"
renamed = "â—"

[jobs]
style = "blue"

[aws]
symbol = "îŒ½ "
disabled = true

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[buf]
format = "via [$symbol]($style)"
disabled = true

[cmake]
format = "via [$symbol]($style)"
disabled = true

[cobol]
format = "via [$symbol]($style)"
disabled = true

[conda]
symbol = "ï„Œ "
disabled = true

[crystal]
format = "via [$symbol]($style)"
disabled = true

[daml]
format = "via [$symbol]($style)"
disabled = true

[dart]
format = "via [$symbol]($style)"
disabled = true

[deno]
format = "via [$symbol]($style)"
disabled = true

[docker_context]
symbol = "ïŒˆ "
disabled = true

[dotnet]
format = "[$symbol(ðŸŽ¯ $tfm )]($style)"
disabled = true

[elixir]
format = 'via [$symbol]($style)'
symbol = "î‰µ "
disabled = true

[elm]
format = 'via [$symbol]($style)'
symbol = "î˜¬ "
disabled = true

[erlang]
format = 'via [$symbol]($style)'
disabled = true

[git_branch]
symbol = "ï˜ "
style = "cyan"

[golang]
format = 'via [$symbol]($style)'
symbol = "î˜§ "
disabled = true

[helm]
format = 'via [$symbol]($style)'
disabled = true

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
disabled = true

[julia]
format = 'via [$symbol]($style)'
symbol = "î˜¤ "
disabled = true

[kotlin]
format = 'via [$symbol]($style)'
disabled = true

[lua]
format = 'via [$symbol]($style)'
disabled = true

[memory_usage]
symbol = "ï¡š "

[nim]
format = 'via [$symbol]($style)'
disabled = true

[nix_shell]
symbol = "ï‹œ "
format = 'via [$symbol($name)]($style) '

[nodejs]
format = 'via [$symbol]($style)'
symbol = "î‰ "
disabled = true

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'
disabled = true

[package]
symbol = "ï£– "
disabled = true

[perl]
format = 'via [$symbol]($style)'
disabled = true

[php]
format = 'via [$symbol]($style)'
symbol = "î˜ˆ "
disabled = true

[pulumi]
format = 'via [$symbol$stack]($style)'
disabled = true

[purescript]
format = 'via [$symbol]($style)'
disabled = true

[red]
format = 'via [$symbol]($style)'
disabled = true

[rlang]
format = 'via [$symbol]($style)'
disabled = true

[ruby]
format = 'via [$symbol]($style)'
symbol = "îˆ¾ "
disabled = true

[rust]
format = 'via [$symbol]($style)'
symbol = "ï€“ "
disabled = true

[swift]
format = 'via [$symbol]($style)'
disabled = true

[vagrant]
format = 'via [$symbol]($style)'
disabled = true

[vlang]
format = 'via [$symbol]($style)'
disabled = true

[zig]
format = 'via [$symbol]($style)'
disabled = true

[env_var.FLOX_PROMPT_ENVIRONMENTS]
format = '([$symbol:$env_value]($style) )'
style = 'green bold'
symbol = 'ó°Š•'

[custom.desk]
description = "indicates whether you're in a desk-spawned shell"
command = "(command -v desk &>/dev/null && desk | grep -q 'No desk activated.') && echo '' || echo ó°‡„"
when = "true"

# [custom.flox_status]
# command = "flox services status --json | jq '[.[].exit_code] | any(. == 1)'"
# detect_folders = [".flox"]
